### PR TITLE
Fix coding style

### PR DESCRIPTION
**Pull request by michael-e**
This PR fixes the coding style according to PSR-2 (and the "Symphony taste").

### CODE REVIEW

**Comment by michael-e** [comment]
Bump.

**Comment by michael-e** [comment]
Bump. :-)

**Comment by nitriques** [comment]
Sorry @michael-e !

**Comment by michael-e** [comment]
No prob. I can bump a lot! :-)

**Comment by nitriques** [comment]
You can tell me to release also ;)

**Comment by michael-e** [comment]
You know what must be done, don't you? ;-)

**Comment by nitriques** [comment]
Yes I do! ;)

**Pull request merged**
